### ISSUE TITLE
Uncertain whether it works

### ISSUE THREAD

**Issue by towynlin** [particle-iot-archived/cc3000-patch-programmer#1]
I attempted to use the patch programmer on the core labeled "Yeah!" today June 4th.

Before doing so, using gdb, I noted that after `nvmem_read_sp_version` the value of `patchVer[1]` was 10.

I programmed the core with the patch programmer binary using JTAG, reset, and hit the button.  Both LEDs began to blink as described in the README.  I waited 10 minutes, and they never stopped blinking.  I powered down the core; plugged it in again, pressed the button, the LEDs started blinking, and I waited 5 minutes before powering it down.

I then reprogrammed the latest usb-dfu using JTAG and st-flash, and the latest logo-turtle marvin application using USB and dfu-util.  The core programmed fine in both cases.

Using gdb, now, after `nvmem_read_sp_version` the value of `patchVer[1]` is 0, which seems wrong.  All the fields in patchVer are 0.

The core works fine—connecting to the wifi network and server as normal.

There are two symptoms of a problem to be fixed:
- LEDs keep blinking
- nvmem_read_sp_version does not retrieve a reasonable version number

**Comment by satishgn** [comment]
Fixed the Patch Programmer issue. The patching should work now.
I tested the patch programmer on STM32VLDiscovery + CC3000_EVAL.

The LEDs should stop blinking after the patching process.
Checkout the latest marvin code. The patchVer should now report "\001\023" i.e. 1.19
I need to check if the above version reported is correct with the latest patch. Do you have any idea?

Can you run the patch programmer on your "Yeah!" and find out the patchVer.

I will try out the programmer on my only Core after getting the confirmation ;-)

**Comment by andyw-lala** [comment]
Is there a pre-built image of both the 1.19 patch programmer and the
running app that I can use to upgrade and test my units ?

If not, can someone please build and check them into git ?

On Wed, Jun 5, 2013 at 7:17 AM, Satish Nair notifications@github.comwrote:

> Fixed the Patch Programmer issue. The patching should work now.
> I tested the patch programmer on STM32VLDiscovery + CC3000_EVAL.
> 
> The LEDs should stop blinking after the patching process.
> Checkout the latest marvin code. The patchVer should now report "\001\023"
> i.e. 1.19
> I need to check if the above version reported is correct with the latest
> patch. Do you have any idea?
> 
> Can you run the patch programmer on your "Yeah!" and find out the patchVer.
> 
> I will try out the programmer on my only Core after getting the
> confirmation ;-)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sprk/cc3000-patch-programmer/issues/1#issuecomment-18971818
> .

## 

Andy

**Comment by towynlin** [comment]
I will run the latest programmer on "Yeah!" this afternoon, and Andy I'll check binaries into all 3 repos: this one, usb-dfu, and marvin.

**Comment by towynlin** [comment]
Confirmed.  10 seconds blinking then solid LEDs.  patchVer thereafter gets reported as "\001\023", i.e., 1.19.
