### ISSUE TITLE
Must work with old bootloader

### ISSUE THREAD

**Issue by towynlin** [particle-iot-archived/cc3000-patch-programmer#4]
A community user reported that the latest master of this repo does not work with existing Cores. Probably broke when aligning with the recent bootloader changes.

https://community.spark.io/t/failed-connecting-to-wifi/648/163?u=zachary

**Comment by satishgn** [comment]
@towynlin, I just tested the latest cc3000-patch-programmer's master binary files on the old bootloader and didn't find any issue. Have posted my reply to the community thread above.
